# Generated by Django 5.0.7 on 2024-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_gfx_published_alter_gfx_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfx',
            name='magn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
