# Generated by Django 5.0.7 on 2024-08-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_gfx_magn'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
