# Generated by Django 5.0.7 on 2024-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_website_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='egsmm',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
