# Generated by Django 5.0.7 on 2024-08-08 12:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_client_published_egsmm_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(upload_to=blog.models.generate_webfilename),
        ),
    ]
