# Generated by Django 5.0.7 on 2024-08-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_website_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='smm',
            name='lang',
            field=models.IntegerField(choices=[(0, 'No lang'), (1, 'English'), (2, 'Russian')], default=2),
        ),
    ]
