# Generated by Django 5.0.7 on 2024-08-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_smm_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='lang',
            field=models.IntegerField(choices=[(0, 'No lang'), (1, 'English'), (2, 'Russian')], default=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='lang',
            field=models.IntegerField(choices=[(0, 'No lang'), (1, 'English'), (2, 'Russian')], default=2),
        ),
        migrations.AddField(
            model_name='egsmm',
            name='lang',
            field=models.IntegerField(choices=[(0, 'No lang'), (1, 'English'), (2, 'Russian')], default=2),
        ),
    ]
