# Generated by Django 5.0.7 on 2024-08-09 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_aboutus_lang_contact_lang_egsmm_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smm',
            name='content',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='lang',
        ),
        migrations.AddField(
            model_name='smm',
            name='en',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
