# Generated by Django 5.0.7 on 2024-08-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_smm_content_remove_smm_lang_smm_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='egsmm',
            name='url1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egsmm',
            name='url2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
