# Generated by Django 5.0.7 on 2024-08-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_egsmm_url1_egsmm_url2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
