# Generated by Django 5.0.7 on 2024-08-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lang',
            field=models.IntegerField(choices=[(0, 'No lang'), (1, 'English'), (2, 'Russian')], default=2),
        ),
    ]
