# Generated by Django 5.0.7 on 2024-08-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.IntegerField(choices=[(0, '---'), (1, 'KRW'), (2, 'USD'), (3, 'RUB')], default=1),
        ),
    ]
