# Generated by Django 5.0.7 on 2024-08-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_service_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
