# Generated by Django 5.0.7 on 2024-08-10 05:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='studio',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='team',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='header',
            name='page',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Home'), (2, 'Video case'), (3, 'Reel'), (4, 'Photography'), (5, 'Grachic Design'), (6, 'Website'), (7, 'SMM'), (8, 'Services'), (9, 'About Studio'), (10, 'Clients'), (11, 'Reviews'), (12, 'Contacts'), (13, 'Make an order'), (14, 'Call me'), (20, 'Order'), (98, 'Success page'), (99, 'Failed page')], default=0),
        ),
    ]
