# Generated by Django 5.0.7 on 2024-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_content_review_content_alter_header_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
