# Generated by Django 5.0.7 on 2024-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_header_short_alter_header_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Very unpleasant'), (2, 'Unpleasant'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
    ]
