# Generated by Django 5.0.7 on 2024-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_review_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.AlterField(
            model_name='header',
            name='page',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Home'), (2, 'Video case'), (3, 'Reel'), (4, 'Photography'), (5, 'Grachic Design'), (6, 'Website'), (7, 'SMM'), (8, 'Services'), (9, 'About Studio'), (10, 'Clients'), (11, 'Reviews'), (12, 'Contacts'), (13, 'Make an order'), (14, 'Call me'), (20, 'Order'), (21, 'Write'), (98, 'Success page'), (99, 'Failed page'), (100, 'Without title  (200) (-300)')], default=0),
        ),
    ]
