# Generated by Django 5.0.7 on 2024-08-10 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_delete_call_alter_header_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='greeting',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
