# Generated by Django 5.0.7 on 2024-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_forwhom_videosam_wedo'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwhom',
            name='en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forwhom',
            name='ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wedo',
            name='en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wedo',
            name='ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
