# Generated by Django 5.0.7 on 2024-08-09 12:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('status', models.IntegerField(choices=[(0, 'Applied'), (1, 'Processing'), (2, 'Closed')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
            ],
        ),
    ]
