# Generated by Django 5.0.7 on 2024-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
